### ISSUE TITLE
Reduced User Experience with Focus on Audio Content Delivery

### ISSUE THREAD

**Issue by lauriemarkle** [IDEMSInternational/parenttext-rohingya-malaysia#1]
[Revised user flows are documented in Draw.io](https://drive.google.com/file/d/1PaYVUYVs4be64UMAKI9XpuQe8bA6ZhFP/view?usp=sharing) and pasted below for transparency: 
**User Experience**
<img width="822" alt="image" src="https://github.com/IDEMSInternational/parenttext-rohingya-malaysia/assets/74552270/7e2a2ad7-a79b-44ca-bfaa-5634f4b0ed09">

- Note: users are largely illiterate 
- Onboarding will happen in-person, in group setting, with a facilitator to aid in enrollment and onboarding questions. Onboarding will also cover pre-course check-in, take_a_pause and lesson_1 (elsewhere known as one_on_one_time_yc) together. 
- 4 subsequent lessons will be received remotely, with push notifications via WhatsApp templates availing new lessons 48 hours after each interaction until all 5 lessons are completed. 
- At the end of the 5th lesson, the parent receives an illustration (not customised as a certificate) as a congratulations
- Final in-person session with facilitator. Facilitator submits a trigger (such as CLOSE) to ask a post-course check-in question. 

**Onboarding**
<img width="856" alt="image" src="https://github.com/IDEMSInternational/parenttext-rohingya-malaysia/assets/74552270/b28ebe96-6a5c-4b26-a7dc-8252aa509004">

- Yellow messages = audio files / assets
- Audio files will have asset overrides for caregiver gender, enabling male caregivers to hear messages from male facilitators. 

**Lessons**
<img width="614" alt="image" src="https://github.com/IDEMSInternational/parenttext-rohingya-malaysia/assets/74552270/f2763c5d-f091-4d57-8bf9-e8ba895056f7">

- Lessons pushed 48hrs after last interaction or accessed early with TBD trigger word that, if it has been at least 24hrs since last lesson was received, a new lesson is sent. 
- Lesson data lists should include lesson_id; asset_text; asset_name

**Closing**
<img width="775" alt="image" src="https://github.com/IDEMSInternational/parenttext-rohingya-malaysia/assets/74552270/f71f658b-2040-4174-b09e-74f9c2bd08b0">

-Closing delivered as text, as it is accessed with 1-on-1 facilitator support

**Safeguarding**
<img width="315" alt="image" src="https://github.com/IDEMSInternational/parenttext-rohingya-malaysia/assets/74552270/03c44812-c200-4847-9043-9ae60ff8c0f9">

-Safeguarding can be accessed at any time with a trigger, but does not include a menu. Safeguarding is sent as a single audio file / asset. 

**Caught Messages / Errors**
<img width="802" alt="image" src="https://github.com/IDEMSInternational/parenttext-rohingya-malaysia/assets/74552270/bfe61a3f-9f95-45d8-8f04-ea802fe6f663">

-Given low literacy of audience, caught messages will receive an audio response for unknown messages.

**Comment by lauriemarkle** [comment]
@fagiothree - Updating some language in the **Closing** flow here for your attention. 
<img width="923" alt="Screenshot 2024-02-22 at 12 52 29 PM" src="https://github.com/IDEMSInternational/parenttext-rohingya-malaysia/assets/74552270/12a0a697-3c35-44ce-8130-ecb696b7ae4d">

**Comment by fagiothree** [comment]
- [ ] Implement goal content algorithm 
- [ ] Implement onboarding
- [ ] Implement timed programme
- [ ] Add audio attachments to Firebase
- [ ] Add completion trophy
- [ ] Define attachment paths
- [ ] Implement safeguarding (111)
- [ ] Add audio to "sorry I don't understand" messages
- [ ] Implement GO trigger functionality
- [ ] Implement CLOSE trigger functionality
