### ISSUE TITLE
Adjusted Notification Schedule

### ISSUE THREAD

**Issue by lauriemarkle** [IDEMSInternational/parenttext-rohingya-malaysia#2]
Notifications for next lesson to be 48 hours instead of 23.5 hours as new lesson each day. This means the closing session can take place after 2 weeks.

The hook message should be sent 
48h + 48h + 48h after last interaction

**Comment by fagiothree** [comment]
parenttext_campaign_events defined in https://docs.google.com/spreadsheets/d/1zclrjl-xMtLk3IizX-VhLjZsO0eSfrVc0wKVRse3qCE/edit#gid=1639521737
