### ISSUE TITLE
Define data lists for modules

### ISSUE THREAD

**Issue by fagiothree** [IDEMSInternational/parenttext-rohingya-malaysia#3]

**Comment by lauriemarkle** [comment]
Module data list structure should include: 
module_id, 10 sets of text and audio assets.

**Comment by fagiothree** [comment]
https://docs.google.com/spreadsheets/d/1BZ6R-aW9FB8OoXKr1nDnAdUwlgc2Q0vYpeEOZ2C9vYY/edit#gid=1602763327
